import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import ClientProvider from '@/providers/ClientProvider';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Brass Business Banking",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <ClientProvider>
     <body
        
        >
          <Header/>
          <main className='lg:mt-28 sm:mt-[39%] w-full'>
            {children}
          </main>
        </body>
     </ClientProvider>
    </html>
  );
}
